theme: jekyll-theme-minimal
repository: STEM-Alliance/STEM-Alliance.github.io
description: Resources & Links
logo: https://github.com/STEM-Alliance/STEM-Alliance.github.io/blob/master/logo.png?raw=true
